services:
  # Web service - Next.js frontend
  - type: web
    name: syb-volume-scheduler-web
    runtime: node
    rootDir: web
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SOUNDTRACK_API_TOKEN
        sync: false
      - key: SOUNDTRACK_API_URL
        value: https://api.soundtrackyourbrand.com/v2
      - key: DATABASE_URL
        fromDatabase:
          name: syb-scheduler-db
          property: connectionString
      - key: MOCK_USERS
        sync: false

  # Background worker - Volume scheduler
  - type: worker
    name: syb-volume-scheduler-worker
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start:db
    envVars:
      - key: NODE_ENV
        value: production
      - key: SOUNDTRACK_API_TOKEN
        sync: false
      - key: SOUNDTRACK_API_URL
        value: https://api.soundtrackyourbrand.com/v2
      - key: DATABASE_URL
        fromDatabase:
          name: syb-scheduler-db
          property: connectionString

databases:
  - name: syb-scheduler-db
    plan: starter # $7/month
    postgresMajorVersion: 15